name: Beach Today

on:
  workflow_dispatch:

#  schedule:
#    - cron: '*/5 * * * *'  # every 5 minutes

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run check
        env:
          NOME: ${{ secrets.NOME }}
          EMAIL: ${{ secrets.EMAIL }}
          NUMERO_MATRICULA: ${{ secrets.NUMERO_MATRICULA }}
          CREDENCIAL_ID: ${{ secrets.CREDENCIAL_ID }}

        run: |
          echo "Current working directory: $PWD"
          echo ls -la
          cd ./project_scripts
          python3 -m venv venv_praia
          source behave_orb/bin/activate
          pip3 install -r requirements.txt
          python main.py
