name: Beach Today

on:
  workflow_dispatch:

#  schedule:
#    - cron: '*/5 * * * *'  # every 5 minutes

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run check
        env:
          NOME: ${{ secrets.NOME }}
          EMAIL: ${{ secrets.EMAIL }}
          NUMERO_MATRICULA: ${{ secrets.NUMERO_MATRICULA }}
          CREDENCIAL_ID: ${{ secrets.CREDENCIAL_ID }}

        run: |
          echo "Current working directory: $PWD"
          cd ./project_scripts
          python3 -m venv venv_praia
          source venv_praia/bin/activate
          pip3 install -r requirements.txt
          python main.py
        id: vaga_para_compra
        continue-on-error: true

  segundo_job:
    runs-on: ubuntu-latest
    needs: verify
    steps:
      - name: Carregar variáveis de ambiente
        run: |
          echo "Current working directory: $PWD"
          ls -la $PWD
          echo "RESULTADO_COMPRA=$(cat $GITHUB_WORKSPACE/resultado_compra.env)" >> $GITHUB_ENV

      - name: Mostrar resultado
        run: echo "O resultado é ${{ env.RESULTADO_COMPRA }}"