name: Beach Today

on:
  workflow_dispatch:

#  schedule:
#    - cron: '*/5 * * * *'  # every 5 minutes

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run check
        env:
          NOME: ${{ secrets.NOME }}
          EMAIL: ${{ secrets.EMAIL }}
          NUMERO_MATRICULA: ${{ secrets.NUMERO_MATRICULA }}
          CREDENCIAL_ID: ${{ secrets.CREDENCIAL_ID }}

        run: |
          pip install -r requirements.txt
